---
- name: "Apache installation using Docker"
  hosts: prod
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
      - files/secrets/credentials.vault
  pre_tasks:
    - name: Install EPEL repo
      package: name={{ item }} state=present
      when: ansible_distribution == "CentOS"
      loop:
        - epel-release
        - git
        - wget

    - name: Install Python 3 and pip3
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker module for Python
      pip:
        name: docker
        executable: pip3
        
  tasks:
    - name: Copy website file template
      template:
        src: index.html.j2
        dest: /home/vagrant/index.html
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes: 
         - /home/vagrant/index.html:/usr/local/apache2/htdocs/index.html
